// templates/monorepo/apps/frontend/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/')({
  component: App,
});

function App() {
  return (
    <div className="text-center">
      <header className="min-h-screen flex flex-col items-center justify-center bg-[#282c34] text-white text-[calc(10px+2vmin)]">
        <h1 className="text-5xl font-bold mb-4">Welcome</h1>
        <p>
          Edit <code>src/routes/index.tsx</code> and save to reload.
        </p>
        <a
          className="text-[#61dafb] hover:underline"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        <a
          className="text-[#61dafb] hover:underline"
          href="https://tanstack.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn TanStack
        </a>
      </header>
    </div>
  );
}

// templates/monorepo-svelte/apps/frontend/src/routes/+page.svelte
<div class="text-center">
  <header
    class="min-h-screen flex flex-col items-center justify-center bg-[#282c34] text-white text-[calc(10px+2vmin)]"
  >
    <h1 class="text-5xl font-bold mb-4">Welcome</h1>
    <p>
      Edit <code>src/routes/+page.svelte</code> and save to reload.
    </p>
    <a
      class="text-[#ff3e00] hover:underline"
      href="https://svelte.dev"
      target="_blank"
      rel="noopener noreferrer"
    >
      Learn Svelte
    </a>
    <a
      class="text-[#ff3e00] hover:underline"
      href="https://elysiajs.com"
      target="_blank"
      rel="noopener noreferrer"
    >
      Learn ElysiaJS
    </a>
  </header>
</div>
